fluendo/cerbero

recipes/couchbase-lite/couchbase-lite.recipe

Add special cases for darwin & windows to the System SQL nuget

Restructure nuget generation of Couchbase

---

recipes/couchbase-lite/couchbase-lite.recipe
recipes/mono/config

Update couchbase recipe to 1.3.1 - VAS-24

---

cerbero/commands/package.py

Get the sha1 from the contents of the file, not the path

---

cerbero/packages/packagesstore.py

Fix for commit 456671056d4dc9ffa92fb30eec3535c34d01f9e8 @turran

Don't override existing packages with the ones from recipes

---

cerbero/config.py
config/linux.config

Allow to add some custom cflags in addtion to the default one.

Introduce custom_cflags var.

---

recipes/fontconfig.recipe

Ra 767 - Add template to the fontconfig recipe

---

cerbero/build/fridge.py

It will already do it in the original file

Don't change the install_name if it's a symlink

---

cerbero/config.py
cerbero/main.py

This reverts commit ffdfeb8cd4b71cb7d481c412c5f17cfe1f064cdd.

Revert "Add cerbero root path to config"

---

cerbero/config.py

No need for reset flag anymore as it should not be
used in load_main_config anymore.

Remove reset flag in _parse method

---

cerbero/build/recipe.py
cerbero/ide/vs/genlib.py

It will replace it in the .def file

Add an optional libname to genlib

---

cerbero/build/cookbook.py

Cerbero can now detect several recipes in a recipe file
with prefix Recipe...
Can be useful when declaring a demo recipe class.

Several recipes in one file.

---

cerbero/build/fridge.py
cerbero/packages/distarchive.py
cerbero/utils/__init__.py

Windows, unix, wine...
Replace the prefix in text files in bin too

Replace the prefix with all the possible paths

---

cerbero/tools/osxrelocator.py
cerbero/utils/__init__.py
recipes/libiconv.recipe
recipes/libiconv/0004-remove-cflagvisibility.patch
recipes/mono.recipe
recipes/mono/mono-osx.recipe
recipes/mono/mono-windows.recipe
recipes/xamarin.mac.recipe

- update mono windows recipe
- add mono-osx recipe

update mono version to 5.0.1.1

---

cerbero/build/source.py
recipes/gst-plugins-good-1.0-static.recipe
recipes/gst-plugins-good-1.0.recipe
recipes/gst-plugins-good-1.0/0001-remove-vpx-old-img_fmt_i420.patch

Remove an old define from vpx library.
OP-27

Fix gst-plugins-good-1.0 build

---

recipes/gstreamer.recipe

Added DEBIAN STRECH support for gstreamer recipe.

---

recipes/gstreamer-static.recipe

Support for Debian 9 (Stretch) in gstreamer-static.

---

recipes/docbook-xml.recipe
recipes/docbook-xsl.recipe
recipes/gtk-doc.recipe
recipes/libxml2.recipe
recipes/libxml2/0002-Add-the-prefix-to-the-default-location-of-the-catalog-file.patch

This PR fixes the installation of the docbook files

Docbook fixes

---

cerbero/config.py
config/linux.config

Remove toolchain prefix and use only the
gcc -m option to define the target architecture.

Fix linux cross compilation: x86_64->x86

---

cerbero/utils/__init__.py
config/windows.config

In order to keep compatibility with buildbot
remove bin from window.config and assemblies it
in get_wix_prefix

Fix wix bin path

---

cerbero/packages/wix_packager.py

Fix f9a5333bbb727bb0ab164c555a82e97cf615dbd3

Extend the wixobjs array only when using fragment

---

cerbero/utils/__init__.py

like lib/libmylibrary -->
lib/something_libmylibrary

Add ability to decorate filename with some prefix

---

cerbero/bootstrap/__init__.py
cerbero/bootstrap/bootstraper.py
cerbero/bootstrap/build_tools.py
cerbero/bootstrap/linux.py
cerbero/commands/bootstrap.py

Add quiet mode for winetricks.

Add quiet mode for wine installation

---

cerbero/bootstrap/linux.py

Remove autopoint and glib-networking for hardy as
for lucid.

Remove undefined package for hardy

---

cerbero/packages/package.py
cerbero/packages/wix.py
data/wix/Config.wxi

Add wix_config_custom variable

Add a way to add custom variable to Config.wxi

---

cerbero/utils/shell.py

Test file exists before removing it.

download_curl: Test dest file during exception

---

cerbero/packages/packagesstore.py

The __file__ can be used in prepare (oneplay-dvd.package)
which is called in _load_package_from_file

Fill __file__ from package in _load_package_from_file

---

cerbero/enums.py
cerbero/utils/__init__.py
config/darwin.config
recipes/mono/mono-osx.recipe
recipes/mono/mono-windows.recipe
recipes/xamarin.mac.recipe

- Update to Xamarin.Mac 4.6.0.14

Add osx mojave to enums & change mono version to 5.12

---

cerbero/utils/svn.py

Helps to know if a given file has been ignored by SVN.

Add is_ignored method

---

cerbero/packages/wix_packager.py

Allow to strip contents of tmpdir in a merge module
using fragments and rmove the folder at the end of the MSI
process.

MSI:Allow to strip content of a tmpdir

---

recipes/gst-plugins-base.recipe
recipes/gst-plugins-good.recipe

Use the last revision of fluendo's gst-plugins-good

---

cerbero/utils/shell.py

Tarfile is generally much slower than tar and specially slower
with xz compression

Improve extraction speed of tarballs

---

cerbero/packages/package.py
cerbero/packages/packager.py
cerbero/packages/wix.py
cerbero/packages/wix_packager.py
config/windows.config

Make use of fragments instead of merge module which
can't be created due to a bug in wine

wix: add support for msi creation in cross-compilation

---

cerbero/bootstrap/linux.py
cerbero/enums.py
cerbero/packages/rpm.py
cerbero/utils/__init__.py

Check:
* https://gitlab.freedesktop.org/gstreamer/cerbero/merge_requests/301
* https://gitlab.freedesktop.org/gstreamer/cerbero/merge_requests/305

Hotfix yum centos

---

cerbero/packages/rpm.py

This allows to use i.e. '%(files)s' inside postinstall or postremove
scripts to get the list of files in the package instead of hardcoding them

rpm: Replace templates inside postinstall and postremove scripts

---

cerbero/main.py

Sync with upstream changes for self_update arg: https://gitlab.freedesktop.org/gstreamer/cerbero/merge_requests/411#note_412842

Add self_update args always

---

cerbero/build/build.py

Because both configure methods from CMake class and base class
MakefilesBase are decorated with @async_modify_environment, the
following error appears when trying to build a CMake project recipe
with use_system_libs equals True:
+++++++++++++++++++++++++++++
Traceback (most recent call last):
File "./cerbero/cerbero/build/oven.py", line 202, in _cook_recipe
loop.run_until_complete(stepfunc(recipe))
File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
return future.result()
File "./cerbero/cerbero/build/recipe.py", line 54, in wrapped
await ret
File "./cerbero/cerbero/build/build.py", line 170, in call
res = await func(*args)
File "./cerbero/cerbero/build/build.py", line 595, in configure
await MakefilesBase.configure(self)
File …

Allow building CMake recipes using system libraries

---

recipes/build-tools/cmake.recipe
recipes/openjpeg.recipe

Sync CMake changes from https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/417

Sync cmake fixes from upstream

---

cerbero/build/build.py
cerbero/build/cookbook.py
cerbero/build/oven.py
cerbero/build/recipe.py
cerbero/build/source.py
cerbero/commands/check.py
cerbero/commands/fetch.py
cerbero/tools/depstracker.py
cerbero/tools/strip.py
cerbero/utils/git.py
cerbero/utils/shell.py

This commit is basically a cherry-pick of
96180b64c0e9d23f41e803669d1f9e5cf37579a8 from gstreamer upstream getting
rid of non-compatible changes with our forked repo.

Fix log_step_output() behavior when wrapping asynchronous functions

---

cerbero/build/cookbook.py

This fixes an issue when removing symbolic links and directories detected during the installation

Quick fix for symbolic links to directories

---

cerbero/build/cookbook.py

Commit 382273e1f655c80df6263bb3899324659ded2eab introduced a
regression because `installed_files` is kept to be able to clean
old files when installing the new version of a recipe.
However, this made the recipes to be kept in the status, which
caused too many resets when unnecessary.

COM-1152 Fix recipes reset when not needed

---

cerbero/build/recipe.py

According to getmro() doc, the order in which classes are returned
may differ if there is a metaclass such as MetaRecipe. Hence, we
need to ensure the order is always the same for consistency.

OPE-874 Fix recipes reset due to base classes order change

---

cerbero/build/oven.py

On Windows, we need to collect the list of installed files
after the gen_library_file step, while on macOS, we need to
do it before the relocate_osx_binaries.

OPE-902 Fix .def and .lib files missing on fridge packages

---

cerbero/build/cookbook.py

This generated an unwanted delay because it needs to run git ls-remote on the existing recipes that are Git-based just to know whether they need to be invalidated/reset or not. Using the strict recipe checksum this is not needed because rather than relying on some parent maybe changing the built_version, we can rely on the checksum of all of them instead. It's more reliable and faster.This should avoid cases such as http://ci.fluendo.lan:8080/view/ffmpeg/job/fluffgst/job/OCP-1598/39/console:
```+ ./cerbero-uninstalled -t -c projects/fluffgst/patch/fluffgst-patch-release-0.10.cbc gen-manifest-cbc fluffgst-patch-2.0-0.10 fluffgst-patch-2.1-0.10 fluffgst-patch-2.2-0.10 fluffgst-patch-2.3-0.10 fluffgst-patch-2.4-0.10 fluffgst-patch-2.5-0.10 fluffgst-patch-2.6-0.10 fluffgst-patch-2.7-0.10 …
```

Speed up load_recipes a lot when using Git sources and fridge

---

recipes/build-tools/meson.recipe
recipes/build-tools/meson/0002-meson-Centos7-use-platform-installation-folders.patch

Pure variable default value is set to False so we keep the previous versions behavior.

Add Centos7 patch for meson 0.55.3

---

cerbero/build/oven.py

Before this change, even if the package was already extracted,
update_installed_files was called because the one that knew
whether fridge steps were necessary to run was fridge. Now,
the oven also considers this and will only update the files
when no fridge package extraction is done OR when an
install or post_install step is actually run.
Context: test recipe has all steps done but `needs_build=True`. 
The issue is not so much about the warning but about the fact that the installed_files were set to empty.
Before:
```
./cerbero-uninstalled -t -c cerbero/test.cbc build libffi zlib --use-binaries
0:00:00.001728 Loading default configuration from /home/pablo/.cerbero/cerbero.cbc
0:00:00.174499 Building the following recipes: test libffi bzip2 zlib
0:00:00.181915 Fridge initialized with …
```

Only update installed files when files are actually installed

---

cerbero/build/source.py
cerbero/commands/fetch.py

* Consolidate async fetch in fetch command
The fetch_print_wrapper was actually never used. We had some code
redundancy
* Improve query of step_done when reusing repo

OCP-2140 Small fixes to reuse flu-plugins repo for all recipes

---

cerbero/build/source.py

The buildone command enables recipe.force

OCP-2274 Force fetch with the buildone command

---

cerbero/utils/shell.py

Without it it's failing when trying to access
"https://www.agner.org/optimize/objconv.zip"

utils: change User-Agent of urllib's request

---

docs/packaging.md

COM-5433 cerbero - document part of the packaging process

---

README.md

Simple improvements.
To be continued with fluendo-cerbero README

README.md: move sub-module version & setups.

---

cerbero/build/build.py

fix meson install
