fluendo/cerbero

- recipes/build-tools/libtool.recipe
- recipes/build-tools/libtool/0001-Fix--as-needed.patch
It was adding the as-needed flag at the end, when it needs to be before the libs to link
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=347650
> Add patch for -as-needed flag in libtool

- cerbero/config.py
Allow to change the global build dir where cerbero
creates the build artifacts.
> Introduce global_build_dir

- packages/vas-deps.package
This will be solved when bundling longomatch to protect the app,
we should think if we let that dependencies or removed after bundling
to reduce package size.
> LON-974: Add required dependencies for Sparkle

- cerbero/packages/debian.py
Same thing was already done for those scripts while packaging
rpm (commit 6320598c58266d48e05f6b4b2b57ce3f89517ea7)
> debian: Replace %(files)s template inside postinstall and postremove scripts

- recipes/gtk-sharp/gtk-sharp-2.0.recipe
This fixes the pixbuf memory leaks (commit https://github.com/mono/gtk-sharp/commit/f610d89c3e510ba75349b876cb83a5a26a472d0e)
> Update gtk-sharp to version 2.12.45

- cerbero/bootstrap/linux.py
Continues INF-165: build support for Debian 9 (Stretch).
> Debian: Add intltool to apt-get list.

- cerbero/build/build.py
- cerbero/build/filesprovider.py
- cerbero/build/recipe.py
This is needed so that we can generate the documentation for every plugin.
> Add flag to enable/disable gtkdoc when building with autotools

- recipes/build-tools/gettext-m4.recipe
- recipes/build-tools/gettext-tools.recipe
- recipes/build-tools/gettext-tools/secure_snprintf.patch
- recipes/build-tools/m4.recipe
- recipes/build-tools/m4/secure_snprintf.patch
- recipes/glib.recipe
- recipes/glib/secure_snprintf.patch
- recipes/gnutls.recipe
- recipes/gnutls/secure_snprintf.patch
correctly on OSX 10.13 High Sierra
same patch (with difference in start line and paths sometimes)
also applies for:
- glib
- gnutls
- build-tools/gettext-tools
- build-tools/gettext-m4
> recipes/build-tools/m4: add patch for m4 from macports, so it works

- cerbero/bootstrap/build_tools.py
- cerbero/build/recipe.py
This PR adds gtk-doc dependency to the build tools instead of the recipe
> Add gtk-doc to the build tools if the docs variant exists

- recipes/gnutls.recipe
Curl fails on fetching from gnutls's website by ftp.
> recipes/gnutls : fetch from https instead of ftp

- recipes/fribidi.recipe
fribidi.org/download is not valid anymore.
Use VLC repository instead
> Fix url for fribidi package

- cerbero/build/source.py
This will make cerbero apply new or changed patches on already builded
recipes
> Remove build dir during extraction of Git based repo

- recipes/mingw-runtime.recipe
The static version of libstdc++ is necessary to get
rid of dynamic dependencies.
> Copy the static version of libstdc++

- cerbero/bootstrap/linux.py
Use wineconsole only when DISPLAY is not set.
> Set WINE env var to wineconsole only without DISPLAY

- cerbero/packages/wix.py
The install dir is different in the case of an app
installer or not. The Fragment class containing the files
should use SDKROOTDIR instead of INSTALLDIR in the case
of non app.
See: _add_install_dir in MSI class
> WIX fragment should take 'is_app' into account

- recipes/couchbase-lite/couchbase-lite.recipe
It failed on windows with
Could not load type 'Microsoft.Build.Construction.SolutionParser' from assembly 'Microsoft.Build, Version=4.0.0.0'
> Fix couchbase nuget restore

- recipes/couchbase-lite/couchbase-lite.recipe
It checks the VERSION env var to generate the AssemblyInfo used for versioning, and we generate it using TextTransform (we added the NuGet in our couchbase fork)
> LMA-321 - Set the version correctly in the couchbase build process

- cerbero/bootstrap/build_tools.py
- cerbero/bootstrap/linux.py
- cerbero/bootstrap/osx.py
- cerbero/bootstrap/windows.py
- cerbero/build/source.py
- cerbero/config.py
- cerbero/utils/shell.py
After mirror url implementation, download_curl
needs also to support the mirroring system.
> Fix when download_curl replace download

- recipes/openssl.recipe
Fix libssl.dll.a 555 permission preventing the reinstall
of the binaries with extract_binary.
> Fix the openssl devel files permissions

- cerbero/config.py
In order to be used corfrectly by BUILD_TOOLS in build_tools.py
The variable should be initialized as an array.
> extra_build_tools should be initialized to array

- cerbero/bootstrap/windows.py
Copy libntdll.a to the right toolchain folder,
seen that the other toolchain folder could be
missing.
> Copy libntdll.a only in the arch folder

- recipes/libvpx.recipe
- recipes/libvpx/0007-bump-ios-supported-version-to-7.patch
Use patch from upstream repo to bump the version
to 7.0
> libvpx: bump ios minimum version

- recipes/libffi.recipe
- recipes/libffi/0002-disable-unsupported-deprecated-call.patch
Disable the call to 'deprecated' with parameter
unsupported by old gcc versions
> Disable deprecated extended call

- recipes/gst-plugins-base.recipe
- recipes/gst-plugins-base/0002-Explicitly-added-SSE-support.patch
- recipes/gstreamer.recipe
- recipes/gstreamer/0002-also-check-for-winpthread.patch
- recipes/libtheora.recipe
- recipes/libtheora/0008-Do-not-redefine-for-mingw.patch
- recipes/libtheora/0009-remove-cr-rl.patch
On gstreamer:
------------
- Also check for winpthread library
In new versions of mingw clock_gettime and other time functions
are not longer part of the standard library, they have been
moved to wipthread library instead
This patch applies a patch into gstreamer's configure.ac in
order to check if clock_gettime is being provided by winpthread
On libtheora:
------------
- Do not redefine rint function for mingw
All versions of mingw correctly define 'rint' function in
math.h
However, only newer versions complain about the function
redefinition when the -O option is greater than zero
(the redefinition of having a const version for something
that was previously non-const)
Cleanest solution is do not redefine this function for
GNU-C family of compiler and use the compiler's
version instead. …
> Several changes for Mingw >5.3 compatibility

- cerbero/packages/distarchive.py
- cerbero/packages/linux.py
- cerbero/packages/rpm.py
In order to support rpm distrib lib scheme,
need to install the libs in lib64
> rpm packager install lib in lib64

- recipes/build-tools/orc.recipe
To support gstreamer-1.0 > 1.14, we need to bump the version
of orc to 0.4.28
> orc: use gstreamer's community last version

- recipes/mono/mono-windows.recipe
- When application quits even if we Destroy the webkit webviews
they still have threads alive making the application do not close.
this only happens in windows
> Go back to Mono 5.2.0 to fix bug of webkit thread still alive

- recipes/gtk-sharp/gtk-sharp-windows-2.0.recipe
It's still getting the dlls from the installed bin, but we should end up using the recipe for both systems
> Update gtk-sharp to 2.12.43

- cerbero/bootstrap/linux.py
Fix "undefined variable 'a'" when bootstraping on these
platforms
> Fix broken patch for Debian Stretch/Ubuntu Bionic bootstrap

- cerbero/build/fridge.py
- cerbero/build/relocatabletar.py
A new class inheriting TarFile with
relocation abilities was created.
It contains the former logic used in the Fridge
to relocate .tar.bz2 packages
Class is created with mininum coupling to allow
reusing it from other modules
> Decouple code for relocate Fridge's tar files

- cerbero/config.py
Remove array because it is not longer used. Last code
at fluendo_cerbero uses recipes_commits instead
> Remove unusued binary_commits

- cerbero/build/build.py
For some special multilib recipes,
we need to change meson's _builddir
in order to configure in several
passes.
> Allow configure Meson's builddir

- cerbero/config.py
Decrease the desired value to 2048 as it's enough and
attempting to set it to higher values may fail on
some systems when running as a non-root user.
> cerbero: Fix rlimit set exception

- cerbero/build/oven.py
- cerbero/commands/fetch.py
When a recipe that creates a static library is rebuilt,
all reverse dependencies should be rebuilt to pick the last changes.
For example, if libvpx is configured to generate a static library
and the recipe is rebuilt, gst-plugins-bad should all be rebuilt
so that the plugin is linked against the latest build of libvpx.
> static: force rebuild of reverse deps for static recipes

- cerbero/enums.py
- cerbero/utils/__init__.py
Add enum entry and detection for the new macOS Catalina
> Fix cerbero for macOS Catalina

- cerbero/bootstrap/linux.py
CentOS 7.x (RHEL 7.x also) is based on Fedora 19 and it uses yum
as a default package manager.
> bootstrap: Fix dnf usage on CentOS

- cerbero/bootstrap/windows.py
The mingw-6.0.0-gcc-8.2.0-windows-multilib.tar.xz files didn't contain an include folder and we change the Windows.py for creating it
> Create mingw/multilib/x86_64-w64-mingw32/include on bootstrap

- cerbero/utils/git.py
The git credentials need to be set in the repo we're cloning into, not
the repo we're cloning from.
From: https://gitlab.freedesktop.org/gstreamer/cerbero/commit/42db9ec6c8e3f75b41b94cc39077adbf9972f4b6
> cerbero: Fix setting of git credentials

- cerbero/packages/rpm.py
If `%define debug_package %{nil}` is used then `%__spec_install_post` doesn’t
include `__debug_install_post`. And `__debug_install_post` includes the
execution of `/usr/lib/rpm/find-debuginfo.sh`, which it is the one
that extracts debug info from bins and libs.
Code from /usr/lib/rpm/macros
```
%__spec_install_post\
%{?__debug_package:%{__debug_install_post}}\
%{__arch_install_post}\
%{__os_install_post}\
%{nil}
```
Undefining `_debugsource_packages` and `_debuginfo_subpackages` the debuginfo
and debugsource RPM packages are not generated and the rpmbuild process keeps
extracting debug info from the files (`find-debuginfo.sh` is called).
> Fix not strip files in centos7

- cerbero/build/filesprovider.py
Necessary to use /lib/lib64 in centos
> Use lib_suffix in filesprovider

- cerbero/config.py
Added GIO_MODULE_DIR environment variable to shell, so we can use built glib modules instead of bootstrapped.
> Add GIO_MODULES_DIR env var

- cerbero/packages/rpm.py
Fix:
```
rpmbuild -bb --buildroot /workspace/tmpn0_oh6lc/buildroot --target x86_64-redhat-linux /workspace/tmpn0_oh6lc/ffmpeg-fluendo-gst-1.0.spec
...
error: Empty %files file /opt/ffmpeg-fluendo-gst-ci-1.0-redhat_8-x86_64/tmpn0_oh6lc/BUILD/ffmpeg-fluendo-gst-1.0-1.0.8.2/debugfiles.list
RPM build errors:
Empty %files file /opt/ffmpeg-fluendo-gst-ci-1.0-redhat_8-x86_64/tmpn0_oh6lc/BUILD/ffmpeg-fluendo-gst-1.0-1.0.8.2/debugfiles.list
```
Commit 100ed216cd7ae72074bed48c73cc3d8bd2e571cb fixed `Empty %files file ...debugsourcefiles.list`. Now the problem is with `debugfiles.list`
> rpm: Use nodebuginfo option in rpmbuild when exist

- cerbero/packages/rpm.py
Strings algebra problem
```
"redhat_6" > "fedora_26"
```
> rpm: fix distro_version comparison

- cerbero/build/cookbook.py
- cerbero/commands/edit_cache.py
This `cache` command is meant to be used during development to ease and speed up testing and figuring out issues.
The key idea is to have an inspector and modifier of cookbook's status that `pickle` serializes/deserializes to/from both for  `build-tools.cache` and `linux_x86_64.cache` (on Linux).
Usage:
```
usage: cerbero-uninstalled cache [-h] [--bootstrap]
[--steps [STEPS [STEPS ...]]]
[--needs_build NEEDS_BUILD] [--mtime MTIME]
[--file_path FILE_PATH]
[--built_version BUILT_VERSION]
[--file_hash FILE_HASH] [--touch]
[recipe [recipe ...]]
positional arguments:
recipe                Recipe to work with
optional arguments:
-h, --help            show this help message and exit
--bootstrap           Use bootstrap's cache file
--steps [STEPS [STEPS ...]]
Modify steps
--needs_build …
```
> Add cache command to inspect and modify local cache

- cerbero/config.py
When not cross-compiling, $CERBERO_PREFIX/lib path was added at the end
of LD_LIBRARY_PATH whereas build-tools/lib path was prepended. As a
consequence, libraries and tools installed during bootstrap were taking
precedence over the one built later within the prefix (for libraries and
tools available at both places). This happens for example with glib when
it is installed during bootstrap (glib-tools.recipe) and built later as
a dependency (glib.recipe). This commit prepends $CERBERO_PREFIX/lib in
LD_LIBRARY_PATH in order to use the build-tools/lib when no dependency
is custom built, and then to use the $CERBERO_PREFIX/lib once the
dependency has been correctly built. It also brings coherency with PATH
variable order as $CERBERO_PREFIX/bin preceeds build-tools/bin.
> Prepend $CERBERO_PREFIX/lib path in LD_LIBRARY_PATH

- cerbero/build/cookbook.py
- cerbero/packages/packagesstore.py
- cerbero/utils/shell.py
Ensure that at most 64 concurrent `git ls-remote` are run to avoid Bitbucket refusing requests
> Fix after fridge merge

- cerbero/build/source.py
We need to make sure the recipe.cached_built_version is always set because otherwise PackagesStore._package_from_recipe will attempt to run an even loop within an existing loop when calling recipe.built_version().
> Fix to allow catching exceptions in git.get_hash()

- cerbero/config.py
Cross compiling for Linux x86 inside x86_64 the prefix is executable and
the PATH is updated with bindir (`/build/dist/linux_x86/bin`), but
LD_LIBRARY_PATH is not updated with libdir (`/build/dist/linux_x86/lib`).
Same logic to add to PATH should be done to add to LD_LIBRARY_PATH.
Error fixed:
```
./cerbero-uninstalled -t -c cross-linux-x86.cbc build freetype
...
0:05:11.642423 -----> Extracting tarball to /build/sources/linux_x86/freetype-2.9
bzip2: error while loading shared libraries: libbz2.so.1: cannot open shared object file: No such file or directory
tar: Child returned status 127
tar: Error is not recoverable: exiting now
...
```
Inside the shell
```
ldd /build/dist/linux_x86/bin/bzip2
linux-gate.so.1 =>  (0xf7f17000)
libbz2.so.1 => not found
libc.so.6 => …
```
> Update LD_LIBRARY_PATH when the prefix is executable and PATH is updated

- cerbero/config.py
We cannot use the translated version of CC because it doesn't contain any real absolute path.
> Fix CC_VERSION retrieval using original CC

- cerbero/main.py
In case argv[0] is not 'cerbero-uninstalled', the self_update arg is never added. This fix allow us to run cerbero in profilers such as scalene without the error:
```
Scalene: An exception of type AttributeError occurred. Arguments:
("'Namespace' object has no attribute 'self_update'",)
Traceback (most recent call last):
File "/home/pablo/.local/lib/python3.6/site-packages/scalene/scalene.py", line 454, in main
exec(code, the_globals)
File "./cerbero-uninstalled", line 14, in <module>
main()
File "./cerbero/cerbero/main.py", line 196, in main
Main(sys.argv[1:])
File "./cerbero/cerbero/main.py", line 62, in __init__
self.self_update()
File "./cerbero/cerbero/main.py", line 129, in self_update
if not self.args.self_update:
AttributeError: 'Namespace' object has no attribute 'self_update' …
```
> Fix for non-existing self_update args

- cerbero/utils/git.py
Change lost with the update to 1.0: https://github.com/fluendo/cerbero/commit/b80fde557999de9e8daa44d12a6eec3ac503b482
> Fix tags update with git fetch --tags

- cerbero/build/build.py
CMake 3.10.2 has some weird behavior that we can extrapolate to some other old versions:
- Old CMake versions don't support -S, so we use -H instead
- Old CMake versions don't work with whitespace after -H or -B
> Fix CMake issue with older versions

- cerbero/utils/git.py
Apparently, adding --tags makes old git versions to fetch only tags and no branches. The behavior was modified in git 1.9 to fetch both branches and tags:
https://stackoverflow.com/a/20608181
> Fix fetching in old git versions

- cerbero/build/filesprovider.py
Currently the main packages generetad with cerbero contain symlinks for
shared libraries without version number. For instance, executing:
```
./cerbero-uninstalled package base-system-1.0
```
The `base-system-1.0_1.16.1-1_amd64.deb` contains symlinks like
`libturbojpeg.so`, `libxml2.so` or `libz.so`.
These symlinks are also in the development package. And there is an error when the development
package is installed because the system tries to overwrite a file, which was installed by
the main package.
From debian site:
https://www.debian.org/doc/manuals/maint-guide/advanced.en.html
> Please note that the development package should contain a symlink for the
> associated shared library without a version number.
> E.g.: /usr/lib/x86_64-linux-gnu/libfoo.so -> libfoo.so.1
From the fedora site: …
> Only the dev pkg should contain symlinks for shared libraries w/o version number

- cerbero/commands/package.py
- cerbero/packages/disttarball.py
- cerbero/packages/linux.py
* Fix api usage when packaging a stripped tarball
The usage of pack method in package.py was a too complex. It was done
to do not strip packages when creating a tarball for rpm or debian
packages. Now the pack API usage is simpler and the Linux packager
directly specifies that tarball should not be stripped.
* Fix creating a splitted tarball packages.
Trying to do a stat on a symbolic link linking to a path that does not
exist (like .so files in devel pacakges) ended with an error:
```
~/Workspace/fluendo-cerbero$ ./cerbero-uninstalled -c
./projects/openh264/openh264-release.cbc package openh264 --tarball
...
-----> Creating package for openh264
['lib/libopenh264.so.1.8.0', 'lib/libopenh264.so.4']
Traceback (most recent call last):
File "./cerbero-uninstalled", line 14, in <module>
main() …
```
> Fix tarball packages not being stripped correctly

- cerbero/config.py
Commit 62c77d8e0da15230701c25f016c974beceeda32b added PATH to LD_LIBRARY_PATH when it is unnecessary.
The fact that `PATH` was used for any of the env variables used to calculate the hash used in fridge effectively made that we didn't have 2 machines sharing packages.
> COM-1108 Fix PATH inclusion to LD_LIBRARY_PATH

- cerbero/build/cookbook.py
- cerbero/build/recipe.py
- cerbero/utils/shell.py
Now a recipes' checksum depends not only on the hash of the
file and its file dependencies, but also on the hash
of the classes that it inherits from.
- Remove the mtime checks since they no longer ensure
a recipe's status has not changed
- Invalidate the cache for rdeps of a static library if its
cache has been invalidated. This is the same logic that is
done in the fetch command
- Add messages to clearly show that a recipe's cache
has been invalidated
> COM-1107 Improve recipe's checksum to improve consistency

- cerbero/build/recipe.py
Step 'delete_rpath' is custom and might be activated by setting
extra_property['no_rpath'] to True in the cbc. When this is done, all
installed ELF files that are specified in the recipe will have the rpath
removed.
More info from task description:
https://fluendo.atlassian.net/browse/OCP-1353
I'm also going to create a marge request to upstream cerbero.
> Add custom step that removes rpath from binaries on linux

- cerbero/build/recipe.py
Turns out that recipes in fluendo-cerbero have one extra level of indirection, where the top 'Recipe' is in the 'builtins' module while the next 'Recipe' is in None. This fixes the following issue:
```
Traceback (most recent call last):                                                                                                                                                                          
File "./cerbero-uninstalled", line 14, in <module>                                                                                                                                                        
main() …
```
> Fix issue trying to get source lines of builtin

- cerbero/build/fridge.py
Upload first the checksum to use it as a lock resource
so that the rest don't upload anything *if the checksum
is the same*. If the checksum changes, both the checksum
and the package will be overwritten. That's ok, though.
As long as the recipe is the same, packages are equally
usable.
> COM-1158 Decrease possibility of upload contention using fridge

- cerbero/build/cookbook.py
- cerbero/build/oven.py
- cerbero/build/recipe.py
- cerbero/commands/uninstall.py
- cerbero/utils/shell.py
Previous logic didn't work properly when the files were never actually copied because they were the same.
New step is added: `clean_old` which doesn't run the uninstall step which may be quite slow on some machines (e.g. Windows), but ensures the previous list of installed files is manually removed prior to the install step.
> OPE-875 Remove installed_files before installing the new ones

- cerbero/commands/uninstall.py
This will allow recipes to override their clean_installed_files as needed, making the uninstall command compliant.
> OPE-875 Use clean_installed_files instead of manual file deletion

- cerbero/build/relocatabletar.py
- cerbero/tools/osxrelocator.py
This comes from an error backporting fridge from master to 1.0. This is the original code: https://github.com/fluendo/cerbero/blob/master/cerbero/build/relocatabletar.py#L17-L39
I fixed the relocations of text files (some of them which are not considered ASCII text by the `file` command but still require to be relocated. e.g. autotools scripts) but didn't include the code to properly relocate dylib's :facepalm:
> OPE-884 Fix dylib's not relocated using fridge in macOS

- recipes/libkate.recipe
- recipes/libkate/0001-Remove-unnecessary-link-against-liblex-for-kateenc.patch
kateenc links unnecessarily against flex, while flex has an undefined symbol needed that cannot be resolved at link time: yylex.
> OPE-889 Fix libkate compilation in newer gcc versions

- cerbero/build/fridge.py
- cerbero/build/relocatabletar.py
- cerbero/packages/disttarball.py
Some files may have paths that are outside of the prefix. e.g. gnustl.pc contains config.toolchain_prefix path, which on Android is outisde of config.prefix. Without changing this, it's not possible to relocate the packages.
> HS-3667 Add CERBERO_TOOLCHAIN_PREFIX relocation

- cerbero/build/oven.py
There may be the case in which we only build one recipe which is very fast building (e.g. openh264) that may cause trouble.
> Fix missing files on fridge packages generated by Windows native

- cerbero/build/filesprovider.py
On Windows py_prefix is detected as 'Lib' whereas recipes still install
their python files in the posix prefix: 'lib/python[version]'. So we
override the py_prefix in FilesProvider on Windows in order to fetch
python files from the right place.
> Override FilesProvider py_prefix on Windows

- cerbero/build/source.py
- cerbero/commands/fetch.py
- cerbero/utils/__init__.py
- cerbero/utils/git.py
This workaround only works for the git calls that are done outside the fetch step. Within the fetch step, the right environment is already set, so there's no issue there. Outside of fetch steps, the prefix libraries are used before the system ones. The issue happens because git is taking the GnuTLS from the prefix. This is an older version that doesn't support what a new git supports and hence the trouble.
> [OPE-909] Fix GnuTLS issue by forcing git commands to use system's libs

- cerbero/build/filesprovider.py
Decide to look up in lib/ or lib64/ according cerbero's config
`libsufix`.
Issue: OCP-1634
> filesprovider: Look for devel libraries in lib or lib64

- config/windows.config
Even if we set in default cerbero.cbc config something different,
since the default OS config is parsed afterwards, it overrides
the configuration value.
> Allow parallel builds on Windows

- cerbero/build/cookbook.py
We need to ensure the steps list is empty, rather than
relying on built_version and needs_build being on their
default value, since when recipes are half-built they are
still in their default value but may still need to be reset.
> OCP-1699 Fix recipes not reset if checksum changes when half-built

- cerbero/build/cookbook.py
In short, if we're using the strict recipe checksum (which we are, on the CI), there's no need to check if the built_version changed because of any of the parents. Collecting the built_version for a recipe which source is Git and where it's downloaded using fridge, involves calling `git ls-remote` to collect the hash of the commit, since there is no local repo available.
This is a proper fix for the same issue that commit 413f327a4af53d6e005d89f41c062e614bbbdcc5 attempted to fix.
However, it did not really bypass the built_version collection. This one does.
> Fix performance issue collectig the built_version

- cerbero/packages/packagesstore.py
AttributeError: 'App' object has no attribute '__file__' was always
happening when parsing oneplay-dvd.package because at the prepare()
method, the __file__ attribute was not set yet. This commit ensures
it's set before calling any method.
> Fix annoying attibute __file__ not found

- cerbero/commands/bootstrap.py
- cerbero/commands/fetch.py
This is done for compatibility reasons, because it simplifies
our CI logic so that we can pass exactly the same argument
to all of the commands.
> Add --fridge to act as if --use-binaries has been passed

- cerbero/commands/uninstall.py
Initially, I left on purpose the local sources untouched so that we don't need to re-fetch from start. However, the typical use case for this is to remove everything related to a recipe so that we don't need to explicitly fetch before building again. Thus if zlib recipe changes and we want to get rid of previous files:
```
time ./cerbero-uninstalled -t -c projects/codecs/1.0/cross-win64.cbc uninstall zlib
time ./cerbero-uninstalled -t -c projects/codecs/1.0/cross-win64.cbc fetch zlib
time ./cerbero-uninstalled -t -c projects/codecs/1.0/cross-win64.cbc buildone zlib
```
can be simply done by
```
time ./cerbero-uninstalled -t -c projects/codecs/1.0/cross-win64.cbc uninstall zlib
time ./cerbero-uninstalled -t -c projects/codecs/1.0/cross-win64.cbc buildone zlib
```
> Remove also local sources when uninstalling

- cerbero/build/fridge.py
- cerbero/build/recipe.py
Add checksum of deps to make it safer
Even though sometimes the recipe can be the same,
the resulting artifact can be different. An example
is when the configure for a given recipe does something
different in case of different versions of its dependencies.
e.g. flu-codec-sdk and the files it includes depends
on the version of glib.
This way, we make the checksum more robust.
Before
```
./cerbero-uninstalled -t -c projects/codecs/0.10/native.cbc buildone flu-codec-sdk --use-binaries
...
0:00:01.252552 WARNING: Package 'ftp://officestorage1.fluendo.lan/data/fluendo/tech/public/cerbero-binaries-1.0/f8d40391/flu-codec-sdk-linux-x86_64-1.0+git~5049634c-0f6adcfe-devel.tar.bz2' not found
./cerbero-uninstalled -t -c projects/codecs/0.10-glib-2.58/native.cbc buildone flu-codec-sdk --use-binaries …
```
> OCP-1781 Add checksum of deps to make it safer

- cerbero/commands/list.py
```
./cerbero-uninstalled -t -c projects/codecs/1.0/native.cbc list -v
0:00:00.001785 Loading default configuration from /home/pablo/.cerbero/cerbero.cbc
0:00:00.899345 a52dec - 0.7.4 (current checkout: ) - /home/pablo/Fluendo/fluendo-cerbero/cerbero/recipes/a52dec.recipe
0:00:00.899583 autoconf - 2.69 (current checkout: ) - /home/pablo/Fluendo/fluendo-cerbero/cerbero/recipes/build-tools/autoconf.recipe
0:00:00.899712 automake - 1.15.1 (current checkout: ) - /home/pablo/Fluendo/fluendo-cerbero/cerbero/recipes/build-tools/automake.recipe
0:00:00.899790 bison - 3.6.4 (current checkout: ) - /home/pablo/Fluendo/fluendo-cerbero/cerbero/recipes/build-tools/bison.recipe
...
```
```
./cerbero-uninstalled -t -c projects/codecs/1.0/native.cbc list-packages -v
0:00:00.002336 Loading default …
```
> Pass -v/--verbose to show filepaths in list commands

- cerbero/commands/list.py
- recipes/libffi.recipe
This comes from upstream patch where it was preferred that it's shown by default: https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/662#note_726791
> Show file by default on list command

- cerbero/build/fridge.py
- cerbero/utils/shell.py
This is a clear and easy to fix mistake. My guess is that happened during a refactoring of self.remote, but it the code as it was doesn't make any sense. We have not seen any issue with the download method because we're using aftp for that. The upload method is ok, but file_exists and download are completely wrong:
Before. It uploads ENVIRONMENT file no matter it exists already or not because file_exists is broken:
```
tree ~/Fluendo/fridge && ./cerbero-uninstalled -c projects/codecs/1.0/native.cbc edit-cache libffi --steps 'install', 'extract', 'clean_installed_files', 'generate_binary', 'configure', 'post_install', 'delete_rpath', 'compile', 'fetch' && ./cerbero-uninstalled -c projects/codecs/1.0/native.cbc build libffi --upload-binaries && tree ~/Fluendo/fridge …
```
> Fix Ftp class for not working with the proper remote_url

- recipes/gst-editing-services-1.0.recipe
- recipes/gst-libav-1.0.recipe
- recipes/gst-omx-1.0.recipe
- recipes/gst-plugins-bad-1.0.recipe
- recipes/gst-plugins-base-1.0.recipe
- recipes/gst-plugins-good-1.0.recipe
- recipes/gst-plugins-ugly-1.0.recipe
- recipes/gst-rtsp-server-1.0.recipe
- recipes/gst-validate.recipe
- recipes/gstreamer-1.0.recipe
This allows to infer details about the recipe using introspection
outside of the recipe folder more accurately. For example; before
this change using the function inspect.getmro to get the path of a
recipe in the recipes folder from it's class; making this call from
a function outside of the recipes  folder, it will return the class
refreence custom.GStreamer. The problem is if there is another
custom.py in the scope you are calling getmro from. The function
inspect.getmro will do a best guess and may not reference the
correct custom.py. So, by turning the recipes folder in to a module
we get the full class name resolution of recipes.custom.GStreamer;
instead of custom.GStreamer. This avoids any confusion to which
custom.py we are referring to.
> Recipe module for explicit module name resolution

- cerbero/main.py
Fix Windows freeze with async tasks
On Windows, it seems working with async subprocesses and using
PIPEs to communicate with them has some side-effect when the
process returns error. It seems the pipe of the main process
is not properly closed and the main process hangs.
We have two options: either we sleep for an unknown time to make sure
everything is closed and we are ready to finish the process, or we ask
the OS to kill us.
This fixes issue OPE-1434
> Fix Windows freeze with async tasks

- cerbero/bootstrap/build_tools.py
PR for OPE-1352 introduced a bug in https://github.com/fluendo/cerbero/pull/329
when porting from the community
https://gitlab.freedesktop.org/gstreamer/cerbero/-/commit/efd76aec55ef79e16b76ab2f3779c1ff5b2dc8bf#83d1eb23a2f59cbcfcf605b052cfcabc56517232_107_115
The cmake dependency needs to be added not only when fetching recipes,
but also when building them.
> Fix CMake built missing

- cerbero/build/fridge.py
Previously, the remote hash was only checked when local file
already existed to avoid doing networking as much as possible
relying on local cache. However, this has been proven to be
cause of issue. Thus, let's be explicit and pedantic and use
the checksum for files properly.
From now on, if the remote checksum does not match the file,
we assume it's a corrupted file. So, the recipe will be built
from scratch and re-uploaded.
Corrupted files are possible because of error when uploading
the files through FTP.
> Ensure fridge's package integrity

- cerbero/build/source.py
- cerbero/utils/git.py
In some cases, multiple recipes in a cbc may point to the same
git repo. The previous behaviour was to fetch for if recipe. In
this commit, when the repo_dir among multiple recipes is the
same, then only one of them will be fetched and the other
ignored.
There are two cases to ignore fetching a recipe:
- The recipe was already fetch according the recipe status
- There is other similar recipe fetching
An asyncio condition is used per group of recipes pointing to a
common git source. It is used to prevent the fetch step done if
there is an-in-progress fetch (for its source); so if the
in-progress feth fails, the others waiting are not considered
fetched in the cache file.
Issue: OCP-1914
> source: git: Avoid cloning common sources multiple times

- cerbero/bootstrap/build_tools.py
Commit 3208cb85fefe31564cb9249bff0cfad1aa4ce772 fixed one issue
but didn't fully covered all cases. It turns out that the build
tools (only CMake as of now) need to be checked after the bootstrap
has done the apt/yum installation.
Previous commit moved the logic to the `start` step, forgetting that
`fetch_recipes` also needs to consider the same. We could do that with
a decorator for both `start` and `fetch_recipes`, but I do not think
it is worth it for what we need to do right now. So, let's keep it
simple and add it in both sides.
> OCP-2037 Fix CMake not included in fetch step if needed

- cerbero/bootstrap/build_tools.py
- cerbero/build/fridge.py
- cerbero/build/recipe.py
- cerbero/commands/check_binaries_remote.py
- cerbero/commands/fetch.py
- cerbero/utils/shell.py
- docs/fridge.md
Add a new `check-binaries-remote` command to check whether remote binaries in fridge exists or not:
```
./cerbero-uninstalled -t -c cerbero/test.cbc check-binaries-remote zlib; echo $?
0:00:00.001785 Loading default configuration from /home/pablo/.cerbero/cerbero.cbc
0:00:00.037679 Fridge initialized with environment hash fb61b54d
0:00:00.184435 -----> Checking if fridge package exists fb61b54d/zlib-linux-x86_64-1.2.11-f5a8fab9-devel.tar.bz2
0:00:00.188274 ***** Error running 'check-binaries-remote' command:
0:00:00.188297 Package 'ftp://localhost:2121/fb61b54d/zlib-linux-x86_64-1.2.11-f5a8fab9-devel.tar.bz2' not found
1
```
```
./cerbero-uninstalled -t -c cerbero/test.cbc check-binaries-remote test; echo $?
0:00:00.001669 Loading default configuration from …
```
> OCP-2166 Add check-binaries-remote command

- cerbero/config.py
- cerbero/utils/shell.py
- docs/fridge.md
This is a trade-off to favor simplicity and speed
over safety. The reasoning behind this is that if
we do not need the compiler version, we can use
fridge before bootstrapping with consistency. Take
into account that bootstrap process may install a
different or newer compiler version.
Thus, this way we can use check-binaries-remote
before doing anything at all without needing to
bootstrap first. In any case, we add some nice
info for both host and target to ensure minimum
ABI compatibility.
> OCP-2170 Use host and target info for env instead of compiler  version

- cerbero/config.py
Commit bd6f1200b70c08ef2f57bd53729e5fc0f4069b7a added to env vars
a myriad of keys that are only needed to take into account for
the config hash that is used for fridge.
It turns out that for .NET the `PLATFORM` env needs to be something different.
Let's be conservative and use the key-value paris that are needed just for fridge
separate. This explains why `CC_VERSION` was added at this stage :)
> OCP-2170 Fix environment vars set unnecessarily just for fridge

- cerbero/config.py
- docs/fridge.md
This ensures that recipes that have different logic
depending on the variant don't clash when generating
the fridge package.
> OPE-1599 Add CERBERO_VARIANTS to env checksum for fridge

- cerbero/build/recipe.py
- cerbero/build/source.py
For some reason, fluendo-sdk recipe includes duplicated
deps. Also, they might be included in different order.
So, let's do some defensive programming in all the lists
considered for the checksum of the recipe to ensure
consistency across different runs.
This was already done for the parents checksum, but I
wrongly assumed that list_deps() returned a sorted list.
> OCP-2216 Fix different checksum depending on deps order

- cerbero/utils/shell.py
For some reason, offficestorage's FTP server now replies
with an empty line and closes the connection when trying
to download a file that does not exist. As a workaround,
let's only try to download files after verifying that
they actually exist.
> OPE-1636 Workaround for FTP server not replying 550

- cerbero/utils/git.py
It skips an error when fetching submodules (which is the default behaviour) in repos not using submodules.
Supporting fail, would involve touching too much parts of fluendo-cerbero, and we prefer to avoid that and keep it simple.
> OCP-2206: git: Prevent fetching submodules if no git modules present

- cerbero/build/fridge.py
- cerbero/build/oven.py
- cerbero/build/recipe.py
- cerbero/commands/fetch.py
- cerbero/errors.py
- cerbero/utils/shell.py
- docs/fridge.md
- recipes-test/test.recipe
- recipes-test/test2.recipe
- recipes-test/test3.recipe
- recipes-test/test4.recipe
- test.cbc
This PR does some heavy and important refactoring to how fridge is implemented.
Before, most of the logic was kept separately within fridge.py on purpose to ease integration with upstream cerbero.
Now, it's completely integrated in the oven so that fridge steps can be considered as any other kind of step. This allows to finally fix the completion percentage:
Before, percentage completely broken once any fridge step was involved:
```
~/Fluendo/fluendo-cerbero on  1.0 [$!?] via 🐍 v2.7.18
13:24:37 ❯ ./cerbero-uninstalled -t -c cerbero/test.cbc build test4 --fridge
0:00:00.001683 Loading default configuration from /home/pablo/.cerbero/cerbero.cbc
0:00:00.007565 WARNING: Variant static is unknown or obsolete
0:00:00.007684 WARNING: Variant va is unknown or obsolete
0:00:00.020446 WARNING: …
```
> OCP-2247 Fix percentage shown in build steps that include fridge

- cerbero/build/fridge.py
- cerbero/build/oven.py
- docs/fridge.md
4240234c4b0d36dfa0df79fd5d415e7d2f11db72 refactoring of
fridge introduced this subtle but important bug.
TL;DR I forgot to check for the `force` parameter in two
different places when micro-optimizing two paths.
> OCP-2349 Fix buildone command not working after fridge refactoring

- cerbero/commands/package.py
- cerbero/packages/debian.py
- cerbero/packages/package.py
- cerbero/packages/rpm.py
Added set of variables to hold lists of packages that are:
- provided by the package
- conflicting with it
- replaces or obsoleted by the package.
These values will be set to corresponding tags when creating a Debian
or Redhat package.
More information about 'Provides', 'Conflicts' and
'Replaces'/'Obsoletes' tags:
https://www.debian.org/doc/debian-policy/ch-relationships.html
https://rpm.org/user_doc/dependencies.html
> OCP-2383 Optional lists of conflicting, provided and replaced packages

- cerbero/tools/osxrelocator.py
It fails with message "*** is not a Mach-O file"
> OSX: don't try to relocate ar archives

- cerbero/utils/shell.py
Error:
```
$ tar xvf automake-1.15.1.tar.xz
$ cd automake-1.15.1
$ ls -l
total 1520
-rw-r--r-- 1 jenkins jenkins   1516 Jun 18  2017 aclocal.m4
-rw-r--r-- 1 jenkins jenkins    553 Dec 20  2015 AUTHORS
drwxrwxr-x 2 jenkins jenkins   4096 Jun 19  2017 bin
-rwxrwxr-x 1 jenkins jenkins   3995 Jun 17  2017 bootstrap
-r--r--r-- 1 jenkins jenkins 816626 Jun 19  2017 ChangeLog
-rwxrwxr-x 1 jenkins jenkins 232853 Jun 18  2017 configure
-rw-rw-r-- 1 jenkins jenkins  22833 Jun 18  2017 configure.ac
drwxrwxr-x 4 jenkins jenkins   4096 Jun 19  2017 contrib
-rw-rw-r-- 1 jenkins jenkins  17987 Jun 17  2017 COPYING
drwxrwxr-x 3 jenkins jenkins   4096 Jun 19  2017 doc
-rwxrwxr-x 1 jenkins jenkins  13940 Jun 16  2017 gen-testsuite-part
-rw-rw-r-- 1 jenkins jenkins   3300 Jun 16  2017 GNUmakefile
-rw-rw-r-- …
```
> git: Fix issue with last security patch

- cerbero/build/source.py
- recipes/glib.recipe
- recipes/glib/0001-meson-Define-__GCC_HAVE_SYNC_COMPARE_AND_SWAP_4-on-G.patch
When trying to build a recipe that uses both git and CMake, the following error message is shown:
CMake Error: The source directory "/home/jorge/cerbero/sources/android_universal/armv7/my-package-1.2" does not appear to contain CMakeLists.txt.
When using CMake:
self.build_dir == ARCH/PACKAGE-VERSION/_builddir (Path where Git extracts sources)
and
self.config_src_dir == ARCH/PACKAGE-VERSION (Path where Git should extract sources)
The problem is that Git class "extracts" sources to self.build_dir.
build_dir is the path to put binaries (as explained in the message of commit 2d520bfd)
Sources have to be extracted to self.config.sources:
- Tarball Class extracts the sources to self.config.sources.
- self.config.sources is also the path where patches are applied.
Note: Cherry-picked by …
> source: fix Git extraction path for CMake recipes

- cerbero/tools/osxrelocator.py
When sending filename instead of object_file, i.e. full path to file, the command 'file -bh filename' is not able to find the find the file. Therefore, the function will return False always that fileext is different than '.dylib'.
Issue: OCP_3452
> osxrelocator: Provide object_file to is_mach_o_file in change_id

- config/linux.config
GStreamer configure.ac uses a test program for check if unaligned access is possible. The safer or more conservative value for this is zero because it's been used for set the macro `GST_HAVE_UNALIGNED_ACCESS` which chooses between faster and slower implementations for read/swap integers from a memory buffer.
Issue: OCP_3624
> linux.config: Fix gstreamer cross compilation

- cerbero/utils/__init__.py
Otherwise:
File "..../cerbero/cerbero/utils/__init__.py", line 333, in system_info
raise FatalError("Distribution '%s' not supported" % str(d))
cerbero.errors.FatalError: Fatal Error: Distribution '('Gentoo', '2.9', 'n/a')' not supported
> ﻿Modern Gentoo distr adaptation

- README.md
Without this note, it's not clear if the project is self-hosted or is a part of the Fluendo-Cerbero project.
Some useful links are added.
> README.md: Adding Fluendo specific notes.

- cerbero/utils/git.py
In `cerbero.utils.git.ensure_user_is_set()`: forgotten git_dir argument for checking the existence of account's default identity (user.{email,name}).
As a result the check was performed on the build current directory (‘.’).
For example, I had problems with bootstrap stage for "libtool -> extract":
```
[(4/15 @ 25%) automake -> post_install]
[(5/15 @ 26%) libtool -> fetch]
[(5/15 @ 27%) libtool -> extract]
-----> Extracting tarball to /home/maxatka/Fluendo/fluendo-cerbero/my_build_dir/fluendo-codecs-1.20-linux-x86_64/sources/build-tools/libtool-2.4.6
Unpacking /home/maxatka/Fluendo/fluendo-cerbero/my_build_dir/fluendo-codecs-1.20-linux-x86_64/sources/local/libtool-2.4.6/libtool-2.4.6.tar.xz in /home/maxatka/Fluendo/fluendo-cerbero/my_build_dir/fluendo-codecs-1.20-linux-x86_64/sources/build- …
```
> ﻿Forgotten current directory for git config command (name&email).

- cerbero/bootstrap/emscripten.py
Rust version, 1.84.0, will use emsdk 3.1.68 and this unblocks issues with gst-plugins-rs
> Update emscripten to 3.1.68
